name: build-and-smoke-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: dnsbrute-min:test

      - name: Smoke test (short timeout)
        run: |
          docker run --rm \
            -e DOMAIN=example.com \
            -e THREADS=2 \
            -e BATCH_LINES=5000 \
            -e MAX_RECORDS=100 \
            -e RUN_TIMEOUT_SEC=10 \
            dnsbrute-min:test || true
          echo "Listing outputs (if any)"
          docker run --rm dnsbrute-min:test bash -lc 'ls -la /app/wordlists && head -n 3 /app/wordlists/static.txt' 